// <auto-generated />
using System;
using GymFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724075145_AddSalesEntities")]
    partial class AddSalesEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymFlow.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 520, DateTimeKind.Utc).AddTicks(8493),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "المكملات الغذائية",
                            NameEn = "Supplements",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 520, DateTimeKind.Utc).AddTicks(8497)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 520, DateTimeKind.Utc).AddTicks(8504),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الإكسسوارات",
                            NameEn = "Accessories",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 520, DateTimeKind.Utc).AddTicks(8505)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.GymSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Day", "Gender", "StartTime")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("GymSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9735),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9739)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9747),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9748)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9751),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9752)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9755),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9756)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9760),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9761)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9769),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 521, DateTimeKind.Utc).AddTicks(9769)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Active\n2. Inactive\n3. Suspended\n4. Unsuspended");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BirthDate = new DateOnly(1995, 5, 15),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3259),
                            Email = "ahmed@gmail.com",
                            FullName = "Ahmed Mohamed",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000001",
                            RegisterDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3260)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BirthDate = new DateOnly(1998, 8, 20),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3272),
                            Email = "sara@gmail.com",
                            FullName = "Sara Ali",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "01000000002",
                            RegisterDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3273)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BirthDate = new DateOnly(1990, 3, 10),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3280),
                            Email = "mohamed@gmail.com",
                            FullName = "Mohamed Hassan",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000003",
                            RegisterDate = new DateOnly(2026, 1, 10),
                            Status = "Suspended",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 524, DateTimeKind.Utc).AddTicks(3281)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberAttendances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateOnly(2026, 1, 15),
                            CheckIn = new TimeOnly(8, 0, 0),
                            CheckOut = new TimeOnly(10, 0, 0),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3302),
                            IsDeleted = false,
                            MemberId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3303)
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateOnly(2026, 1, 16),
                            CheckIn = new TimeOnly(7, 30, 0),
                            CheckOut = new TimeOnly(9, 30, 0),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3313),
                            IsDeleted = false,
                            MemberId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3314)
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateOnly(2026, 1, 15),
                            CheckIn = new TimeOnly(17, 0, 0),
                            CheckOut = new TimeOnly(18, 30, 0),
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3319),
                            IsDeleted = false,
                            MemberId = 2,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 523, DateTimeKind.Utc).AddTicks(3320)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("Active = 1\nInactive = 2\nExpired = 3\nCancelled = 4\nSuspended = 5\nUnsuspended = 6");

                    b.Property<int>("SubscriptionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SubscriptionTypeId");

                    b.ToTable("MemberSubscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8544),
                            EndDate = new DateOnly(2026, 1, 31),
                            IsDeleted = false,
                            MemberId = 1,
                            Price = 50m,
                            StartDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            SubscriptionTypeId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8547)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8561),
                            EndDate = new DateOnly(2026, 4, 5),
                            IsDeleted = false,
                            MemberId = 2,
                            Price = 130m,
                            StartDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            SubscriptionTypeId = 2,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8562)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8568),
                            EndDate = new DateOnly(2026, 1, 10),
                            IsDeleted = false,
                            MemberId = 3,
                            Price = 450m,
                            StartDate = new DateOnly(2025, 1, 10),
                            Status = "Expired",
                            SubscriptionTypeId = 3,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 525, DateTimeKind.Utc).AddTicks(8568)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "PRD-000001",
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 527, DateTimeKind.Utc).AddTicks(5760),
                            IsDeleted = false,
                            NameAr = "بروتين",
                            NameEn = "Whey Protein",
                            PurchasePrice = 25000m,
                            Quantity = 30,
                            ReorderLevel = 5,
                            SalePrice = 35000m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 527, DateTimeKind.Utc).AddTicks(5763)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Code = "PRD-000002",
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 527, DateTimeKind.Utc).AddTicks(5774),
                            IsDeleted = false,
                            NameAr = "قفازات",
                            NameEn = "Gym Gloves",
                            PurchasePrice = 7000m,
                            Quantity = 50,
                            ReorderLevel = 10,
                            SalePrice = 10000m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 527, DateTimeKind.Utc).AddTicks(5775)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9691),
                            IsDeleted = false,
                            ProductId = 1,
                            PurchaseInvoiceId = 1,
                            Quantity = 10m,
                            Total = 2000m,
                            UnitPrice = 200m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9693)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9702),
                            IsDeleted = false,
                            ProductId = 2,
                            PurchaseInvoiceId = 1,
                            Quantity = 5m,
                            Total = 1500m,
                            UnitPrice = 300m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9703)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9707),
                            IsDeleted = false,
                            ProductId = 3,
                            PurchaseInvoiceId = 2,
                            Quantity = 6m,
                            Total = 1800m,
                            UnitPrice = 300m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9708)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9712),
                            IsDeleted = false,
                            ProductId = 4,
                            PurchaseInvoiceId = 3,
                            Quantity = 5m,
                            Total = 950m,
                            UnitPrice = 190m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 528, DateTimeKind.Utc).AddTicks(9713)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Unpaid\n2. Partial\n3. Paid");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseInvoices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(58),
                            InvoiceDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "PI-000001",
                            IsDeleted = false,
                            PaymentStatus = "Paid",
                            SupplierId = 1,
                            TotalAmount = 3500m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(59)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(71),
                            InvoiceDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "PI-000002",
                            IsDeleted = false,
                            PaymentStatus = "Partial",
                            SupplierId = 2,
                            TotalAmount = 1800m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(72)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(78),
                            InvoiceDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "PI-000003",
                            IsDeleted = false,
                            PaymentStatus = "Unpaid",
                            SupplierId = 1,
                            TotalAmount = 950m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 531, DateTimeKind.Utc).AddTicks(79)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchasePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Cash\n2. Bankak\n3. Fawry");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchasePayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000m,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(246),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bankak",
                            PurchaseInvoiceId = 1,
                            ReferenceNo = "TRX-10001",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(247)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500m,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(260),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Fawry",
                            PurchaseInvoiceId = 1,
                            ReferenceNo = "TRX-10002",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(261)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(267),
                            IsDeleted = false,
                            PaymentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bankak",
                            PurchaseInvoiceId = 2,
                            ReferenceNo = "TRX-10003",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 532, DateTimeKind.Utc).AddTicks(268)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Unpaid\n2. Partial\n3. Paid\n4. Cancelled");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("MemberId");

                    b.ToTable("SalesInvoices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(7994),
                            Discount = 0m,
                            InvoiceDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "INV-0001",
                            IsDeleted = false,
                            MemberId = 1,
                            NetAmount = 150m,
                            Notes = "Monthly membership + product",
                            PaidAmount = 150m,
                            RemainingBalance = 0m,
                            Status = "Paid",
                            SubTotal = 150m,
                            Tax = 0m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(7995)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(8010),
                            Discount = 20m,
                            InvoiceDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "INV-0002",
                            IsDeleted = false,
                            MemberId = 2,
                            NetAmount = 230m,
                            Notes = "Gold subscription",
                            PaidAmount = 100m,
                            RemainingBalance = 130m,
                            Status = "Partial",
                            SubTotal = 250m,
                            Tax = 0m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(8011)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(8019),
                            Discount = 0m,
                            InvoiceDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNo = "INV-0003",
                            IsDeleted = false,
                            NetAmount = 80m,
                            Notes = "Walk-in customer",
                            PaidAmount = 0m,
                            RemainingBalance = 80m,
                            Status = "Unpaid",
                            SubTotal = 80m,
                            Tax = 0m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 533, DateTimeKind.Utc).AddTicks(8020)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesInvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("SalesInvoiceDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(4983),
                            Description = "Monthly Gym Membership",
                            Discount = 0m,
                            IsDeleted = false,
                            ItemId = 1,
                            ItemType = 2,
                            Quantity = 1m,
                            SalesInvoiceId = 1,
                            Total = 100m,
                            UnitPrice = 100m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(4986)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(4999),
                            Description = "Protein Powder",
                            Discount = 0m,
                            IsDeleted = false,
                            ItemId = 1,
                            ItemType = 1,
                            Quantity = 1m,
                            SalesInvoiceId = 1,
                            Total = 50m,
                            UnitPrice = 50m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(5000)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(5005),
                            Description = "Gold Membership",
                            Discount = 20m,
                            IsDeleted = false,
                            ItemId = 2,
                            ItemType = 2,
                            Quantity = 1m,
                            SalesInvoiceId = 2,
                            Total = 230m,
                            UnitPrice = 250m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(5006)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(5011),
                            Description = "Gym Gloves",
                            Discount = 0m,
                            IsDeleted = false,
                            ItemId = 2,
                            ItemType = 1,
                            Quantity = 1m,
                            SalesInvoiceId = 3,
                            Total = 80m,
                            UnitPrice = 80m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 534, DateTimeKind.Utc).AddTicks(5012)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Cash\n2. Bankak\n3. Fawry");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VoidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoidReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VoidedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("SalesPayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150m,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 535, DateTimeKind.Utc).AddTicks(818),
                            IsDeleted = false,
                            IsVoided = false,
                            Notes = "Full payment",
                            PaymentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ReferenceNo = "REC-0001",
                            SalesInvoiceId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 535, DateTimeKind.Utc).AddTicks(819)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 535, DateTimeKind.Utc).AddTicks(832),
                            IsDeleted = false,
                            IsVoided = false,
                            Notes = "First payment",
                            PaymentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            ReferenceNo = "REC-0002",
                            SalesInvoiceId = 2,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 535, DateTimeKind.Utc).AddTicks(833)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte>("DaysPerWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("DurationDays")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6788),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)30,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شهري",
                            NameEn = "Monthly",
                            Price = 50m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6792)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6805),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)90,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ربع سنوي",
                            NameEn = "Quarterly",
                            Price = 130m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6806)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6810),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)365,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "سنوي",
                            NameEn = "Yearly",
                            Price = 450m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 536, DateTimeKind.Utc).AddTicks(6811)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 537, DateTimeKind.Utc).AddTicks(6417),
                            FullName = "Fitness Nutrition Co.",
                            IsDeleted = false,
                            PhoneNumber = "01000001001",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 537, DateTimeKind.Utc).AddTicks(6419)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 537, DateTimeKind.Utc).AddTicks(6427),
                            FullName = "Elite Sports Supplies",
                            IsDeleted = false,
                            PhoneNumber = "01000001002",
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 537, DateTimeKind.Utc).AddTicks(6428)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5805),
                            FullName = "Ahmed Mohamed",
                            HireDate = new DateOnly(2025, 1, 10),
                            IsDeleted = false,
                            PhoneNumber = "01000000101",
                            Salary = 5000m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5807)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5825),
                            FullName = "Sara Ali",
                            HireDate = new DateOnly(2025, 3, 15),
                            IsDeleted = false,
                            PhoneNumber = "01000000102",
                            Salary = 5500m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5825)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5829),
                            FullName = "Mohamed Hassan",
                            HireDate = new DateOnly(2024, 11, 20),
                            IsDeleted = false,
                            PhoneNumber = "01000000103",
                            Salary = 6000m,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 538, DateTimeKind.Utc).AddTicks(5830)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.TrainerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId", "Day", "StartTime")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TrainerSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5896),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrainerId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5897)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5905),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 6, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 2, 0, 0, 0),
                            TrainerId = 1,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5906)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5910),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 1, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 2,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5911)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5914),
                            Day = "Wednesday",
                            EndTime = new TimeSpan(0, 7, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 3, 0, 0, 0),
                            TrainerId = 2,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5915)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5918),
                            Day = "Thursday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 4, 0, 0, 0),
                            TrainerId = 3,
                            UpdatedAt = new DateTime(2026, 7, 24, 7, 51, 39, 539, DateTimeKind.Utc).AddTicks(5919)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("SubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Product", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchaseDetail", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchasePayment", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchasePayments")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesInvoice", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesInvoiceDetail", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("Details")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesPayment", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("Payments")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.TrainerSchedule", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Trainer", "Trainer")
                        .WithMany("TrainerSchedules")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberAttendances");

                    b.Navigation("MemberSubscriptions");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Product", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseDetails");

                    b.Navigation("PurchasePayments");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SalesInvoice", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Navigation("MemberSubscriptions");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseInvoices");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("TrainerSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
