// <auto-generated />
using System;
using GymFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716093126_MakeMemberAddressAndBirthDateNullable")]
    partial class MakeMemberAddressAndBirthDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Active\n2. Inactive\n3. Suspended\n4. Unsuspended");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BirthDate = new DateOnly(1995, 5, 15),
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2509),
                            Email = "ahmed@gmail.com",
                            FullName = "Ahmed Mohamed",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000001",
                            RegisterDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2509)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BirthDate = new DateOnly(1998, 8, 20),
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2515),
                            Email = "sara@gmail.com",
                            FullName = "Sara Ali",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "01000000002",
                            RegisterDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2516)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BirthDate = new DateOnly(1990, 3, 10),
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2518),
                            Email = "mohamed@gmail.com",
                            FullName = "Mohamed Hassan",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000003",
                            RegisterDate = new DateOnly(2026, 1, 10),
                            Status = "Suspended",
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(2518)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberAttendances", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("Active = 1\nInactive = 2\nExpired = 3\nCancelled = 4\nSuspended = 5\nUnsuspended = 6");

                    b.Property<int>("SubscriptionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SubscriptionTypeId");

                    b.ToTable("MemberSubscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8386),
                            EndDate = new DateOnly(2026, 1, 31),
                            IsDeleted = false,
                            MemberId = 1,
                            Price = 50m,
                            StartDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            SubscriptionTypeId = 1,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8387)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8395),
                            EndDate = new DateOnly(2026, 4, 5),
                            IsDeleted = false,
                            MemberId = 2,
                            Price = 130m,
                            StartDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            SubscriptionTypeId = 2,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8396)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8397),
                            EndDate = new DateOnly(2026, 1, 10),
                            IsDeleted = false,
                            MemberId = 3,
                            Price = 450m,
                            StartDate = new DateOnly(2025, 1, 10),
                            Status = "Expired",
                            SubscriptionTypeId = 3,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 926, DateTimeKind.Utc).AddTicks(8398)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte>("DaysPerWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("DurationDays")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1710),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)30,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شهري",
                            NameEn = "Monthly",
                            Price = 50m,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1710)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1715),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)90,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ربع سنوي",
                            NameEn = "Quarterly",
                            Price = 130m,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1715)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1716),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)365,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "سنوي",
                            NameEn = "Yearly",
                            Price = 450m,
                            UpdatedAt = new DateTime(2026, 7, 16, 9, 31, 23, 927, DateTimeKind.Utc).AddTicks(1717)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("SubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberAttendances");

                    b.Navigation("MemberSubscriptions");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Navigation("MemberSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
