// <auto-generated />
using System;
using GymFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720113943_AddCategoryProductSupplierEntities")]
    partial class AddCategoryProductSupplierEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymFlow.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 319, DateTimeKind.Utc).AddTicks(8837),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "المكملات الغذائية",
                            NameEn = "Supplements",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 319, DateTimeKind.Utc).AddTicks(8840)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 319, DateTimeKind.Utc).AddTicks(8844),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الإكسسوارات",
                            NameEn = "Accessories",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 319, DateTimeKind.Utc).AddTicks(8845)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.GymSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Day", "Gender", "StartTime")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("GymSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3157),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3158)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3163),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3163)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3164),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3165)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3166),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3166)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3168),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Gender = "Male",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3168)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3173),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Gender = "Female",
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(3173)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("1. Active\n2. Inactive\n3. Suspended\n4. Unsuspended");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BirthDate = new DateOnly(1995, 5, 15),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3203),
                            Email = "ahmed@gmail.com",
                            FullName = "Ahmed Mohamed",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000001",
                            RegisterDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3204)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BirthDate = new DateOnly(1998, 8, 20),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3213),
                            Email = "sara@gmail.com",
                            FullName = "Sara Ali",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "01000000002",
                            RegisterDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3214)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BirthDate = new DateOnly(1990, 3, 10),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3216),
                            Email = "mohamed@gmail.com",
                            FullName = "Mohamed Hassan",
                            Gender = 1,
                            IsDeleted = false,
                            PhoneNumber = "01000000003",
                            RegisterDate = new DateOnly(2026, 1, 10),
                            Status = "Suspended",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(3216)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberAttendances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateOnly(2026, 1, 15),
                            CheckIn = new TimeOnly(8, 0, 0),
                            CheckOut = new TimeOnly(10, 0, 0),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8653),
                            IsDeleted = false,
                            MemberId = 1,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8653)
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateOnly(2026, 1, 16),
                            CheckIn = new TimeOnly(7, 30, 0),
                            CheckOut = new TimeOnly(9, 30, 0),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8657),
                            IsDeleted = false,
                            MemberId = 1,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8658)
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateOnly(2026, 1, 15),
                            CheckIn = new TimeOnly(17, 0, 0),
                            CheckOut = new TimeOnly(18, 30, 0),
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8660),
                            IsDeleted = false,
                            MemberId = 2,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 320, DateTimeKind.Utc).AddTicks(8660)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("Active = 1\nInactive = 2\nExpired = 3\nCancelled = 4\nSuspended = 5\nUnsuspended = 6");

                    b.Property<int>("SubscriptionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SubscriptionTypeId");

                    b.ToTable("MemberSubscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8519),
                            EndDate = new DateOnly(2026, 1, 31),
                            IsDeleted = false,
                            MemberId = 1,
                            Price = 50m,
                            StartDate = new DateOnly(2026, 1, 1),
                            Status = "Active",
                            SubscriptionTypeId = 1,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8520)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8531),
                            EndDate = new DateOnly(2026, 4, 5),
                            IsDeleted = false,
                            MemberId = 2,
                            Price = 130m,
                            StartDate = new DateOnly(2026, 1, 5),
                            Status = "Active",
                            SubscriptionTypeId = 2,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8531)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8533),
                            EndDate = new DateOnly(2026, 1, 10),
                            IsDeleted = false,
                            MemberId = 3,
                            Price = 450m,
                            StartDate = new DateOnly(2025, 1, 10),
                            Status = "Expired",
                            SubscriptionTypeId = 3,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 321, DateTimeKind.Utc).AddTicks(8533)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "PRD-000001",
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(1081),
                            IsDeleted = false,
                            NameAr = "بروتين",
                            NameEn = "Whey Protein",
                            PurchasePrice = 25000m,
                            Quantity = 30,
                            ReorderLevel = 5,
                            SalePrice = 35000m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(1083)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Code = "PRD-000002",
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(1089),
                            IsDeleted = false,
                            NameAr = "قفازات",
                            NameEn = "Gym Gloves",
                            PurchasePrice = 7000m,
                            Quantity = 50,
                            ReorderLevel = 10,
                            SalePrice = 10000m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(1089)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte>("DaysPerWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("DurationDays")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5383),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)30,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "شهري",
                            NameEn = "Monthly",
                            Price = 50m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5383)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5390),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)90,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ربع سنوي",
                            NameEn = "Quarterly",
                            Price = 130m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5390)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5391),
                            DaysPerWeek = (byte)7,
                            DurationDays = (short)365,
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "سنوي",
                            NameEn = "Yearly",
                            Price = 450m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(5392)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(8319),
                            FullName = "Fitness Nutrition Co.",
                            IsDeleted = false,
                            PhoneNumber = "01000001001",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(8319)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(8323),
                            FullName = "Elite Sports Supplies",
                            IsDeleted = false,
                            PhoneNumber = "01000001002",
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 323, DateTimeKind.Utc).AddTicks(8323)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1599),
                            FullName = "Ahmed Mohamed",
                            HireDate = new DateOnly(2025, 1, 10),
                            IsDeleted = false,
                            PhoneNumber = "01000000101",
                            Salary = 5000m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1600)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1608),
                            FullName = "Sara Ali",
                            HireDate = new DateOnly(2025, 3, 15),
                            IsDeleted = false,
                            PhoneNumber = "01000000102",
                            Salary = 5500m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1608)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1610),
                            FullName = "Mohamed Hassan",
                            HireDate = new DateOnly(2024, 11, 20),
                            IsDeleted = false,
                            PhoneNumber = "01000000103",
                            Salary = 6000m,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(1610)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.TrainerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId", "Day", "StartTime")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TrainerSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5070),
                            Day = "Sunday",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrainerId = 1,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5071)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5075),
                            Day = "Tuesday",
                            EndTime = new TimeSpan(0, 6, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 2, 0, 0, 0),
                            TrainerId = 1,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5075)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5076),
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 1, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 2,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5077)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5078),
                            Day = "Wednesday",
                            EndTime = new TimeSpan(0, 7, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 3, 0, 0, 0),
                            TrainerId = 2,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5079),
                            Day = "Thursday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            IsDeleted = false,
                            StartTime = new TimeSpan(0, 4, 0, 0, 0),
                            TrainerId = 3,
                            UpdatedAt = new DateTime(2026, 7, 20, 11, 39, 41, 324, DateTimeKind.Utc).AddTicks(5080)
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberAttendance", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.MemberSubscription", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Member", "Member")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("MemberSubscriptions")
                        .HasForeignKey("SubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Product", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.TrainerSchedule", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Trainer", "Trainer")
                        .WithMany("TrainerSchedules")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberAttendances");

                    b.Navigation("MemberSubscriptions");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.SubscriptionType", b =>
                {
                    b.Navigation("MemberSubscriptions");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("TrainerSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
